# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca011b526699dd156a1f9064393ffa79c778a822361f4e6b48f1f784640401d28de0146408611913d973d08c6585813510ab2c980f465d107b8cba3a52a22d1b

test:
  secret_key_base: 506423c71abe9fbccbf2a53cb275c41b3b9c3c908b69be6d08b4325759bd38beadd5a1cdee77cf64150062a0cdc32e8e02c436dc0c2b166f5dbf68ae2d34807d

    # Do not keep production secrets in the unencrypted secrets file.
    # Instead, either read values from the environment.
    # Or, use `bin/rails secrets:setup` to configure encrypted secrets
    # and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET"] %>
  s3_access_key_id: <%= ENV["S3_KEY"] %>
  s3_secret_access_key: <%= ENV["S3_SECRET"] %>
  s3_region: <%= ENV["S3_REGION"] %>

